const gamesProfile = [
  {
    GameID: "kings-queens",
    GameTitle: "Kings & Queens",
    GamesGroup: "Progressive",
    Team: "No",
    Division: "No",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "No",
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points",
    DrawRefresh: "Yes"
  },
  {
    GameID: "survivor",
    GameTitle: "Survivor",
    GamesGroup: "Progressive",
    Team: "No",
    Division: "No",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "No",
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points",
    DrawRefresh: "Yes"
  },
  {
    GameID: "gauntlet",
    GameTitle: "Gauntlet",
    GamesGroup: "Progressive",
    Team: "No",
    Division: "No",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "Yes",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "No",
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points",
    DrawRefresh: "Yes"
  },
  {
    GameID: "out-of-lives",
    GameTitle: "Out Of Lives",
    GamesGroup: "Progressive",
    Team: "No",
    Division: "No",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "Yes",
    Redivisioning: "No",
    PlayOff: "No",
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points",
    DrawRefresh: "Yes"
  },
  {
    GameID: "my-house",
    GameTitle: "My House",
    GamesGroup: "Progressive",
    Team: "No",
    Division: "No",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "No",
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points",
    DrawRefresh: "Yes"
  },
  {
    GameID: "snakes-ladders",
    GameTitle: "Snakes & Ladders",
    GamesGroup: "Progressive",
    Team: "No",
    Division: "No",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "No",
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points",
    DrawRefresh: "Yes"
  },
  {
    GameID: "bridge-the-gap",
    GameTitle: "Bridge The Gap",
    GamesGroup: "Progressive",
    Team: "No",
    Division: "No",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "No",
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points",
    DrawRefresh: "Yes"
  },
  {
    GameID: "eliminations",
    GameTitle: "Eliminations",
    GamesGroup: "Progressive",
    Team: "No",
    Division: "No",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "No",
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points",
    DrawRefresh: "Yes"
  },
  {
    GameID: "rotating-partners",
    GameTitle: "Rotating Partners",
    GamesGroup: "Single Group",
    Team: "No",
    Division: "No",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "Yes",
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points",
    DrawRefresh: "No"
  },
  {
    GameID: "doubles-pro",
    GameTitle: "Doubles Pro",
    GamesGroup: "Single Group",
    Team: "Yes",
    Division: "No",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "Yes",
    PlayOff: "Yes",
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points",
    DrawRefresh: "No"
  },
  {
    GameID: "keep-it-fair",
    GameTitle: "Keep It Fair",
    GamesGroup: "Single Group",
    Team: "No",
    Division: "No",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "Yes",
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points",
    DrawRefresh: "No"
  },
  {
    GameID: "the-two-of-us",
    GameTitle: "The Two Of Us",
    GamesGroup: "Single Group",
    Team: "Yes",
    Division: "No",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "No",
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points",
    DrawRefresh: "No"
  },
  {
    GameID: "divisions",
    GameTitle: "Divisions",
    GamesGroup: "Tiered Groups",
    Team: "No",
    Division: "Yes",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "Yes",
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points",
    DrawRefresh: "No"
  },
  {
    GameID: "teams",
    GameTitle: "Teams",
    GamesGroup: "Tiered Groups",
    Team: "Yes",
    Division: "No",
    Draft: "Yes",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "No",
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points",
    DrawRefresh: "No"
  },
  {
    GameID: "ladder-scramble",
    GameTitle: "Ladder Scramble",
    GamesGroup: "Tiered Groups",
    Team: "No",
    Division: "Yes",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "Yes",
    Lives: "No",
    Redivisioning: "Yes",
    PlayOff: "No",
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points",
    DrawRefresh: "No"
  },
  {
    GameID: "pools",
    GameTitle: "Pools",
    GamesGroup: "Tiered Groups",
    Team: "No",
    Division: "Yes",
    Draft: "Yes",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "Yes",
    PlayOff: "Yes",
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points",
    DrawRefresh: "No"
  },
  {
    GameID: "mid-tier-divisions",
    GameTitle: "Mid Tier Divisions",
    GamesGroup: "Tiered Groups",
    Team: "No",
    Division: "Yes",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "No",
    PlayOff: "Yes",
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points",
    DrawRefresh: "No"
  },
  {
    GameID: "pool-fusion",
    GameTitle: "Pool Fusion",
    GamesGroup: "Tiered Groups",
    Team: "Yes",
    Division: "Yes",
    Draft: "Yes",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "Yes",
    PlayOff: "No",
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points",
    DrawRefresh: "No"
  },
  {
    GameID: "rx-sports",
    GameTitle: "Rx Sports",
    GamesGroup: "Tiered Groups",
    Team: "Yes",
    Division: "No",
    Draft: "Yes",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    Redivisioning: "Yes",
    PlayOff: "Yes",
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points",
    DrawRefresh: "No"
  }
];
