const gamesProfile = [
  {
    GameID: "kings-queens",
    GameTitle: "Kings & Queens",
    GamesGroup: "Progressive",
    Grouping: "None",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "Yes",
      ReDraw: "No",
      PlayOffs: "No",
      ResultRefresh: "Yes"
    }],
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points"
  },
  {
    GameID: "survivor",
    GameTitle: "Survivor",
    GamesGroup: "Progressive",
    Grouping: "None",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "Yes",
      ReDraw: "No",
      PlayOffs: "No",
      ResultRefresh: "Yes"
    }],
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points"
  },
  {
    GameID: "gauntlet",
    GameTitle: "Gauntlet",
    GamesGroup: "Progressive",
    Grouping: "None",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "Yes",
      ReDraw: "No",
      PlayOffs: "No",
      ResultRefresh: "Yes"
    }],
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points"
  },
  {
    GameID: "out-of-lives",
    GameTitle: "Out Of Lives",
    GamesGroup: "Progressive",
    Grouping: "None",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "Yes",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "Yes",
      ReDraw: "No",
      PlayOffs: "No",
      ResultRefresh: "Yes"
    }],
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points"
  },
  {
    GameID: "my-house",
    GameTitle: "My House",
    GamesGroup: "Progressive",
    Grouping: "None",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "Yes",
      ReDraw: "No",
      PlayOffs: "No",
      ResultRefresh: "Yes"
    }],
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points"
  },
  {
    GameID: "snakes-ladders",
    GameTitle: "Snakes & Ladders",
    GamesGroup: "Progressive",
    Grouping: "None",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "Yes",
      ReDraw: "No",
      PlayOffs: "No",
      ResultRefresh: "Yes"
    }],
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points"
  },
  {
    GameID: "bridge-the-gap",
    GameTitle: "Bridge The Gap",
    GamesGroup: "Progressive",
    Grouping: "None",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "Yes",
      ReDraw: "No",
      PlayOffs: "No",
      ResultRefresh: "Yes"
    }],
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points"
  },
  {
    GameID: "eliminations",
    GameTitle: "Eliminations",
    GamesGroup: "Progressive",
    Grouping: "None",
    Draft: "No",
    Rounds: "No",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "Yes",
      ReDraw: "No",
      PlayOffs: "No",
      ResultRefresh: "Yes"
    }],
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points"
  },
  {
    GameID: "rotating-partners",
    GameTitle: "Rotating Partners",
    GamesGroup: "Single Group",
    Grouping: "None",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "No",
      ReDraw: "Yes",
      PlayOffs: "Yes",
      ResultRefresh: "No"
    }],
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points"
  },
  {
    GameID: "doubles-pro",
    GameTitle: "Doubles Pro",
    GamesGroup: "Single Group",
    Grouping: "Teams",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "Yes",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["Yes",100],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "No",
      ReDraw: "Yes",
      PlayOffs: "Yes",
      ResultRefresh: "No"
    }],
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points"
  },
  {
    GameID: "keep-it-fair",
    GameTitle: "Keep It Fair",
    GamesGroup: "Single Group",
    Grouping: "None",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "No",
      ReDraw: "Yes",
      PlayOffs: "Yes",
      ResultRefresh: "No"
    }],
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points"
  },
  {
    GameID: "the-two-of-us",
    GameTitle: "The Two Of Us",
    GamesGroup: "Single Group",
    Grouping: "None",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "No",
      ReDraw: "Yes",
      PlayOffs: "Yes",
      ResultRefresh: "No"
    }],
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points"
  },
  {
    GameID: "divisions",
    GameTitle: "Divisions",
    GamesGroup: "Tiered Groups",
    Grouping: "Divisions",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "No",
      ReDraw: "Yes",
      PlayOffs: "No",
      ResultRefresh: "No"
    }],
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points"
  },
  {
    GameID: "teams",
    GameTitle: "Teams",
    GamesGroup: "Tiered Groups",
    Grouping: "Teams",
    Draft: "Yes",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "No",
      ReDraw: "Yes",
      PlayOffs: "No",
      ResultRefresh: "No"
    }],
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points"
  },
  {
    GameID: "ladder-scramble",
    GameTitle: "Ladder Scramble",
    GamesGroup: "Tiered Groups",
    Grouping: "Divisions",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "Yes",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["Yes",100],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "No",
      ReDraw: "Yes",
      PlayOffs: "No",
      ResultRefresh: "No"
    }],
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points"
  },
  {
    GameID: "pools",
    GameTitle: "Pools",
    GamesGroup: "Tiered Groups",
    Grouping: "Divisions",
    Draft: "Yes",
    Rounds: "Yes",
    CycleRounds: "Yes",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["Yes",100],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "No",
      ReDraw: "Yes",
      PlayOffs: "No",
      ResultRefresh: "No"
    }],
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points"
  },
  {
    GameID: "mid-tier-divisions",
    GameTitle: "Mid Tier Divisions",
    GamesGroup: "Tiered Groups",
    Grouping: "Divisions",
    Draft: "No",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "No",
      ReDraw: "Yes",
      PlayOffs: "No",
      ResultRefresh: "No"
    }],
    Scoring: ["Points","Wins","None"],
    ScoringDefault: "Points"
  },
  {
    GameID: "pool-fusion",
    GameTitle: "Pool Fusion",
    GamesGroup: "Tiered Groups",
    Grouping: "Divisions",
    Draft: "Yes",
    Rounds: "Yes",
    CycleRounds: "Yes",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["Yes",1],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "No",
      ReDraw: "Yes",
      PlayOffs: "No",
      ResultRefresh: "No"
    }],
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points"
  },
  {
    GameID: "rx-sports",
    GameTitle: "Rx Sports",
    Grouping: "Teams",
    Draft: "Yes",
    Rounds: "Yes",
    CycleRounds: "No",
    Lives: "No",
    drawMenuOpt: [{
      Redivisioning: ["No",null],
      AddMatch: "Yes",
      PlayerSub: "Yes",
      PlayerAvailable: "No",
      ReDraw: "Yes",
      PlayOffs: "Yes",
      ResultRefresh: "No"
    }],
    Scoring: ["Points","Wins"],
    ScoringDefault: "Points"
  }
];
